#!/bin/python3

from shoes import shoes

low = shoes("Red Tape",12)
medium = shoes("nike",25)
high = shoes("Adidas",100)

try:
	shoe_budget =float(input("what is your budget?:))
	
except (ValueError):
	exit("please Enter number1")

for shoes in [high, medium, low]:
	shoes.buy(shoe_budget)
	
